#!/bin/bash
# Generated by run_convergence.py -- do not edit; regenerate instead.
# Unattended long run: start under nohup/setsid so it survives logout.
#   setsid nohup ./run_convergence.sh > logs/driver.log 2>&1 < /dev/null &
set -uo pipefail
cd "$(dirname "$(readlink -f "$0")")"
mkdir -p logs

# train_flow.py is launched with --resume, so a retry continues from the newest
# snapshot instead of restarting. Retries are BOUNDED: an unbounded loop turns a
# genuine bug into an infinite burn of two GPUs over a weekend.
MAX_TRIES=3

run_cell() {
  local gpu="$1"; shift
  local tag="$1"; shift
  local try=1
  while [ "$try" -le "$MAX_TRIES" ]; do
    echo "[$(date -Is)] gpu $gpu  $tag  attempt $try/$MAX_TRIES"
    CUDA_VISIBLE_DEVICES="$gpu" "$@" >> "logs/$tag.log" 2>&1 && {
      echo "[$(date -Is)] gpu $gpu  $tag  done"
      return 0
    }
    echo "[$(date -Is)] gpu $gpu  $tag  FAILED (attempt $try)"
    try=$((try + 1))
    sleep 60
  done
  echo "[$(date -Is)] gpu $gpu  $tag  GIVING UP after $MAX_TRIES attempts"
  return 1
}

(
  run_cell 0 "ctrl-e60-conv-s0" /home/andrea/Downloads/SJTU/PointMass3D/.venv/bin/python train_flow.py --data data --n-envs 60 --env-start 0 --out checkpoints/conv/ctrl-e60-conv-s0.pt --epochs 300 --batch 1024 --lr 0.0002 --channels 128 --n-blocks 8 --seed 0 --num-workers 8 --split-by pair --snapshot-every 10 --resume --amp --wandb --wandb-group convergence --wandb-name ctrl-e60-conv-s0
) &
(
  run_cell 1 "treat-e60-conv-s0" /home/andrea/Downloads/SJTU/PointMass3D/.venv/bin/python train_flow.py --data data --n-envs 60 --env-start 0 --out checkpoints/conv/treat-e60-conv-s0.pt --epochs 300 --batch 1024 --lr 0.0002 --channels 128 --n-blocks 8 --seed 0 --num-workers 8 --split-by pair --snapshot-every 10 --resume --reduced --amp --wandb --wandb-group convergence --wandb-name treat-e60-conv-s0
) &

wait
echo "[$(date -Is)] all cells finished; score with:"
echo "  /home/andrea/Downloads/SJTU/PointMass3D/.venv/bin/python run_convergence.py score"
