#.venv/bin/python seed_inventory.py [--tex]

#How many seeds each arm actually has, read from results/conv/.

#Three separate claims about seed counts drifted apart in the manuscripts while
#the runs were still landing: a table caption saying n=2 or 3, a future-work
#entry saying single-seed, and a limitations paragraph saying "several
#ablations". check_paper_numbers.py could not catch any of them, because a
#sentence about how many seeds a cell has contains no number that checker knows.
#This generates the ground truth instead, so the manuscripts can be checked
#against the filesystem rather than against memory.

import argparse
import collections
import json
import pathlib
import re
import statistics as st

#Which epoch counts as "the" result for an arm. The 250-environment runs are 80
#epochs and the 60-environment ones 300, so "last snapshot" is the only rule
#that works for both -- and it must be computed per seed, since a run can be
#killed part-way and would otherwise silently contribute a mid-training score.
RESULTS = pathlib.Path("results/conv")
PAT = re.compile(r"^([a-z0-9]+)-e(\d+)-conv-s(\d)\.ep(\d+)\.json$")


def inventory(root=RESULTS):
    #arm -> {seed: (epoch, free%)}, taking the LAST epoch present for each seed.
    #-kfa3 files are excluded by the pattern's anchored .json: they end in
    #"-kfa3.json" and would otherwise be matched as the same epoch, silently
    #substituting a frame-averaged score for the plain one.
    best = collections.defaultdict(dict)
    for f in sorted(root.glob("*.json")):
        m = PAT.match(f.name)
        if not m:
            continue
        arm, envs, seed, ep = m.group(1), int(m.group(2)), int(m.group(3)), int(m.group(4))
        key = f"{arm}-e{envs}"
        if ep > best[key].get(seed, (-1, 0.0))[0]:
            row = json.load(f.open())
            best[key][seed] = (ep, (row["rows"][0] if "rows" in row else row)["free"])
    return best


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tex", action="store_true",
                    help="emit a LaTeX comment block to paste into the manuscripts")
    args = ap.parse_args()

    best = inventory()
    if not best:
        print(f"no results under {RESULTS}/ -- run this on the machine that has them")
        return 1

    rows = []
    for arm in sorted(best):
        d = best[arm]
        vals = [d[s][1] for s in sorted(d)]
        eps = sorted({d[s][0] for s in d})
        se = st.stdev(vals) / len(vals) ** 0.5 if len(vals) > 1 else None
        rows.append((arm, st.mean(vals), se, len(vals), eps))

    if args.tex:
        print("% Generated by seed_inventory.py -- do not edit by hand.")
        print("% arm & mean & across-seed SE & n & epoch")
        for arm, mu, se, n, eps in rows:
            sestr = f"{se:.2f}" if se is not None else "---"
            print(f"% {arm:<18} {mu:6.2f} & {sestr:>5} & {n} & ep{eps[0] if len(eps)==1 else eps}")
        return 0

    print(f"{'arm':<18} {'mean':>7} {'SE':>6} {'n':>2}  epoch")
    for arm, mu, se, n, eps in rows:
        if len(eps) > 1:
            #Refuse to average across budgets. A killed run leaves partial
            #snapshots that otherwise enter as a full seed: ctrlgeo-e250 once
            #reported 59.81 by averaging an epoch-80 score with an epoch-20 one.
            #Printing a mean with a warning beside it is not enough, because the
            #mean is what gets copied into a table.
            per = "  ".join(f"s{s}:ep{d[0]}={d[1]:.1f}"
                            for s, d in sorted(best[arm].items()))
            print(f"{arm:<18} {'--':>7} {'--':>6} {n:>2}  MIXED EPOCHS, no mean: {per}")
            continue
        sestr = f"{se:.2f}" if se is not None else "  ---"
        print(f"{arm:<18} {mu:7.2f} {sestr:>6} {n:>2}  {eps[0]}")

    n_by = collections.Counter(n for _, _, _, n, _ in rows)
    print("\nseed counts: " + ", ".join(f"n={k}: {v} arms" for k, v in sorted(n_by.items())))
    single = [a for a, _, _, n, _ in rows if n == 1]
    if single:
        print("single-seed arms (must be described as such in both manuscripts):")
        print("  " + ", ".join(single))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
